"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os

# Update paths to reflect new directory structure
APP = ['main.py']
DATA_FILES = [
    ('resources', ['resources/icon.icns']),
]
OPTIONS = {
    'argv_emulation': True,
    'packages': ['rumps', 'pydexcom', 'pandas', 'numpy', 'matplotlib', 'charset_normalizer'],
    'includes': ['cmath', 'chardet'],
    'iconfile': 'resources/icon.icns',
    'plist': {
        'CFBundleName': 'DexcomNavBarIcon',
        'CFBundleDisplayName': 'DexcomNavBarIcon',
        'CFBundleGetInfoString': "DexcomNavBarIcon",
        'CFBundleIdentifier': "com.ericspencer.dexcomnavbaricon",
        'CFBundleVersion': "1.0.0",
        'CFBundleShortVersionString': "1.0.0",
        'NSHumanReadableCopyright': u"Copyright © 2024, Eric Spencer, All Rights Reserved",
        'NSHighResolutionCapable': True,
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
