name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install py2app
        
    - name: Build application
      run: |
        python setup.py py2app
        
    - name: Create DMG
      run: |
        # Create a temporary directory for DMG contents
        mkdir -p dmg_temp
        # Copy the app to the temporary directory
        cp -R "dist/DexcomNavBarIcon.app" dmg_temp/
        # Create a symbolic link to Applications
        ln -s /Applications dmg_temp/Applications
        # Create the DMG
        hdiutil create -volname "DexcomNavBarIcon" -srcfolder dmg_temp -ov -format UDZO DexcomNavBarIcon.dmg
        # Clean up
        rm -rf dmg_temp
        
    - name: Upload DMG
      uses: actions/upload-artifact@v2
      with:
        name: DexcomNavBarIcon
        path: DexcomNavBarIcon.dmg 