name: Build macOS DMG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download and install Python 3.9 universal2
      run: |
        curl -LO https://www.python.org/ftp/python/3.9.13/python-3.9.13-macos11.pkg
        sudo installer -pkg python-3.9.13-macos11.pkg -target /
        python3.9 --version
        which python3.9
        python3.9 -m pip install --upgrade pip
        python3.9 -m pip install virtualenv
        # Set up venv for build.sh if needed
        echo "PYTHON_BIN=$(which python3.9)" >> $GITHUB_ENV
        echo "PATH=/Library/Frameworks/Python.framework/Versions/3.9/bin:$PATH" >> $GITHUB_ENV
    
    - name: Make build.sh executable
      run: chmod +x build.sh

    - name: Run build.sh (build, sign, notarize, create DMG)
      env:
        NOTARIZE_APPLE_ID: ${{ secrets.NOTARIZE_APPLE_ID }}
        NOTARIZE_TEAM_ID: ${{ secrets.NOTARIZE_TEAM_ID }}
        NOTARIZE_APP_SPECIFIC_PASSWORD: ${{ secrets.NOTARIZE_APP_SPECIFIC_PASSWORD }}
        PYTHON_BIN: ${{ env.PYTHON_BIN }}
        PATH: ${{ env.PATH }}
      run: ./build.sh
    
    - name: Upload DMG artifact
      uses: actions/upload-artifact@v4
      with:
        name: DexcomNavBarIcon-dmg
        path: DexcomNavBarIcon.dmg
